tasks:
  - init: |
    python3 -m venv venv
    source venv/bin/activate
    pip3 install -r requirements.txt

github:
  prebuilds:
    branches: true
    master: true

vscode:
  extensions:
    - "mhutchie.git-graph"
    - "ms-python.python"
